google_maps_bus_tracker:
  name: Google Maps Bus Tracker
  description: Track bus information using Google Maps API
  target:
    entity:
      integration: google_maps_bus_tracker
  fields:
    route_number:
      name: Route Number
      description: The bus route number to track
      required: true
      selector:
        text:
    origin:
      name: Origin
      description: Origin coordinates (latitude,longitude)
      required: true
      selector:
        text:
    destination:
      name: Destination
      description: Destination coordinates (latitude,longitude)
      required: true
      selector:
        text:

reload:
  name: Reload
  description: Reload the integration configuration

get_bus_info:
  name: Get Bus Info
  description: Get information about a tracked bus route
  fields:
    route_number:
      name: Route Number
      description: The bus route number to get information for
      required: true
      selector:
        text:

update_bus_route:
  name: Update Bus Route
  description: Update the configuration of a bus route
  fields:
    route_number:
      name: Route Number
      description: The bus route number to update
      required: true
      selector:
        text:
    origin:
      name: Origin
      description: New origin coordinates (latitude,longitude)
      required: false
      selector:
        text:
    destination:
      name: Destination
      description: New destination coordinates (latitude,longitude)
      required: false
      selector:
        text:

track_bus:
  name: Track Bus
  description: Start tracking a new bus route
  fields:
    route_number:
      name: Route Number
      description: The bus route number to track
      required: true
      example: "123"
    origin:
      name: Origin
      description: The origin coordinates or address
      required: true
      example: "52.3676, 4.9041"
    destination:
      name: Destination
      description: The destination coordinates or address
      required: true
      example: "52.3676, 4.9041"

untrack_bus:
  name: Untrack Bus
  description: Stop tracking a bus route
  fields:
    route_number:
      name: Route Number
      description: The bus route number to stop tracking
      required: true
      example: "123" 